language: rust

matrix:
  include:
    - rust: beta

matrix:
  include:
    - rust: nightly

install:
  - bash ci/install.sh
  - export PATH="$PATH:$PWD/gcc/bin:$PWD/qemu"

script:
  - bash ci/script.sh

after_success:
  - set -e
  - bash ci/after-success.sh

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
