[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"
name = "app"
version = "0.1.0"

[profile.release]
codegen-units = 1
lto = true

[dependencies]
cortex-m = "0.5.7"
cortex-m-semihosting = "0.3.1"
log = { path = "../log" }
rt = { path = "../rt" }
